DESimagen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('DESimagen/', views.crypto_view, name='DESimagen'),
]

DESimagen/forms.py
from django import forms

class ImageCryptoForm(forms.Form):
    OPERATION_CHOICES = [
        ('encrypt', 'encrypt'),
        ('decrypt', 'decrypt')
    ]

    TYPE_DES_CHOICES = [
        ('SDES', 'SDES'),
        ('DDES', 'DDES'),
        ('TDES', 'TDES')
    ]

    MODE_CHOICES = [
        ('EBC', 'EBC'),
        ('CBC', 'CBC'),
        ('OFB', 'OFB'),
        ('CFB', 'CFB')
    ]

    image_input = forms.ImageField(required=True, label="Image")
    operation = forms.ChoiceField(choices=OPERATION_CHOICES, label="Operation")
    type_DES = forms.ChoiceField(choices=TYPE_DES_CHOICES, label="DES type")
    mode = forms.ChoiceField(choices=MODE_CHOICES, label="Operation Mode")
    key = forms.CharField(max_length=10, required=False, label="Key")
    IV = forms.CharField(max_length=8, required=False, label="Initialization Vector (IV)")

DESimagen/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ImageCryptoForm
from .image_encryption import *
from tempfile import NamedTemporaryFile
import os
import base64

def get_base64_from_image(image_path):
    with open(image_path, 'rb') as image_file:
        base64_image = base64.b64encode(image_file.read()).decode('utf-8')
    return base64_image

def crypto_view(request):
    if request.method == 'POST':
        form = ImageCryptoForm(request.POST, request.FILES)
        if form.is_valid():
            operation = form.cleaned_data['operation']
            type_DES = form.cleaned_data['type_DES']
            mode = form.cleaned_data['mode']
            image_input = form.cleaned_data['image_input']
            key = form.cleaned_data['key'] or generate_key()  
            IV = form.cleaned_data['IV'] or generate_IV()  
            # Save the uploaded image to a temporary file
            with NamedTemporaryFile(delete=False) as temp_file:
                temp_file.write(image_input.read())
                image_path = temp_file.name

            or_base64 = get_base64_from_image(image_path)
            
            with Image.open(image_path) as img:  # Open the image from the provided path
                pixel_array = np.array(img)      # Convert the image to a NumPy array
                pixel_bytes = pixel_array.tobytes()  # Convert the NumPy array to bytes
            
            img_size = img.size

            if operation == 'encrypt':
                result_bytes = encrypt_image(type_DES, mode, pixel_bytes, key, IV)
            else:
                result_bytes = decrypt_image(type_DES, mode, pixel_bytes, key, IV)

            pixel_array = np.frombuffer(result_bytes, dtype=np.uint8).reshape(img_size[1], img_size[0], -1)
            img = Image.fromarray(pixel_array)

            img.save("encriptada.png")
            enc_base64 = get_base64_from_image("encriptada.png")

            # Remove the temporary image file
            os.remove(image_path)

            context = {
                    'original_image': or_base64,
                    'result_image': enc_base64,
                    'action': operation,
                }

            context['form'] = form
            return render(request, 'DESimagen.html', context)

    else:
        form = ImageCryptoForm()

    context = {'form': form}
    return render(request, 'DESimagen.html', context)

DESimagen/templates/DESimagen.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Cifrado RSA (Imagenes)</title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.3.2-dist/css/bootstrap.min.css' %}" integrity="sha384-rnJUVlfOu2+k9suL3km28zDp0cTtwsU+4d+slceK95i1BSdFfeUJdCfcKyW5J3nl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div style="border: 1px solid #ccc; padding: 10px; margin: 10px;">
        <h2>Cifrado DES (Imagenes)</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="image_input">Image:</label>
            <input type="file" id="image_input" name="image_input" accept="image/*"><br>
        
            <div>
                <label for="id_operation">Operación:</label><br>
                {{ form.operation }}
            </div>
            <div>
                <label for="id_type_DES">Tipo de DES:</label><br>
                {{ form.type_DES }}
            </div>
            <div>
                <label for="id_mode">Modo de Operación:</label><br>
                {{ form.mode }}
            </div>
            <div>
                <label for="id_key">Clave:</label><br>
                {{ form.key }}
            </div>
            <div>
                <label for="id_IV">Vector de Inicialización (IV):</label><br>
                {{ form.IV }}
            </div>
            
            <input type="submit" value="Submit">
        </form>

        {% if original_image %}
        <h2>Original Image</h2>
            <img src="data:image/png;base64,{{original_image}}" alt="Original Image">
        {% endif %}
        
        {% if action == 'encrypt' %}
            <h2>Result</h2>
            <p><strong>Image:</strong></p>
            <img src="data:image/png;base64,{{result_image}}" alt="Encrypted Image">
        {% endif %}

        {% if action == 'decrypt' %}
            <h2>Result</h2>
            <p><strong>Image:</strong></p>
            <img src="data:image/png;base64,{{result_image}}" alt="Decrypted Image">
        {% endif %}
    </div>
    <a href="{% url 'index' %}" class="btn btn-primary">Regresar al Inicio</a>

</body>
</html>